apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: WeatherApi
  description: Artist Lookup
  labels:
    example.com/custom: custom_label_value
  annotations:
    backstage.io/techdocs-ref: dir:.
    example.com/service-discovery: artistweb
    circleci.com/project-slug: github/example-org/artist-website
  tags:
    - dotnet
    - webapi
  links:
    - url: https://admin.example-org.com
      title: Admin Dashboard
      icon: dashboard
      type: admin-dashboard
spec:
  type: service
  lifecycle: experimental
  owner: seanonet
  system: core